### PR TITLE
Add an initial splash screen, a more prominent loader screen, transitions

### PR DESCRIPTION
**Pull request by bmbroom**
Adds a splash screen to the initial browser window.

Makes the loading messages more prominent.

Implements smooth transitions for splash screen display, displaying
loader messages, and showing the loaded NG-CHM.

### CODE REVIEW

**Comment by marohrdanz** [comment]
When I pretended to be a somewhat naive user and tried this out, I was unsure if I could just click 'Choose File' even with the splash screen open. Maybe a little 'X' to allow the user to close it?

I was also expecting the 'sample NG-CHM' link to open a demo NG-CHM right in this tab instead of taking me to a whole different URL in a separate tab (but in general I agree with the changes in b828860)

The first 8-ish times, I didn't notice the subtle '*Waiting for application loading to complete*' on the bottom of the splash screen. Maybe make it bigger and a different color?

**Comment by bmbroom** [comment]
I was supposed to add a comment before the previous eight commits that they are mostly concerned with Widgetizer updates.

Additional commits will be back to splash screen improvements.

**Review by marohrdanz — APPROVED** [review]
I like the splash screen. It works as advertised on my system.

**Review by ChrisWakefield — APPROVED** [review]
I would prefer separating splash screen changes from widgetizer changes, and squashing some commits, some of which are one line, but I'll approve this.

**Pull request merged**
