### PR TITLE
Allow heat map creator to specify a species for link outs that use it.

### PR DESCRIPTION
**Pull request by bmbroom**
Heat map creator can add a species property, which will be used in
link outs that include the species in the url.

Tested with "Homo_sapiens" (default) and "Mus_musculus".

### CODE REVIEW

**Review by marohrdanz — COMMENTED** [review]
I notice there are a few variants in the code being replaced: 'Homo_sapiens', 'homo%20sapiens' (i.e. 'homo sapiens'), 'Homo+sapiens'). These are all being replaced with a default 'Homo_sapiens'. Do all the various linkouts accept 'Homo_sapiens'?

**Review by mstucky — APPROVED** [review]
These changes look good to me.

**Comment by bmbroom** [comment]
Mary: I verified that "Homo_sapiens" and "Mus_musculus" are accepted by all the link outs.

**Review by ChrisWakefield — APPROVED** [review]
Good enough.  This suggests some of the old URLs were wonky in the first place.

**Review by marohrdanz — APPROVED** [review]

**Pull request merged**
