### PR TITLE
modify linkout.js for pca plus plugin

### PR DESCRIPTION
**Pull request by jma7**
Integrate PCA plus plot plugin

### CODE REVIEW

**Review by jmelott — CHANGES_REQUESTED** [review]
Misspelling in alert Linkout.js line 1015
alert("Something wrong in getting extra **covariats** from " + axis.axisName)

Various lines referring to string "PC"
Should the PC string be in a particular location relative to the ".coordinate." string you split on like PC.coordinate.xx.yy or can it be anywhere like aa.coordinate.PC.xy?   If it needs to be in a particular spot, is your code here restricting it to that location?   It looks like it may allow it to be anywhere in the string?  Some parts look for ^PC in a regular expression, others just see if PC is included in coords.

NGCHM/WebContent/javascript/custom/custom.js 
Line 4: 
linkouts.setVersion('2020-04-07');
Shouldn't version number change if you're changing this file?

line 11
src: 'http://localhost:8088/index.html'
Should this be pointing to localhost?
All other plugins point to https://www.ngchm.net

**Review by marohrdanz — APPROVED** [review]
I think these changes are reasonable given the current state of the plugin API.

I think the plugin API is a prime candidate for places to refactor and improve upon. Since we needed to change Linkouts.js for PathwayMapper and now for PCAPlus, this seems like this is a good place to re-evaluate / re-engineer a bit to make the API flexible enough to handle future plugin needs.

**Comment by ChrisWakefield** [comment]
@jma7 Conflicts must be resolved.  custom.js is just one line (the version), but I don't know which is right in Linkout.js.

**Comment by bmbroom** [comment]
Working on a more general solution.

**Pull request closed without merging**
