### PR TITLE
Run prettier on .js files and update actions

### PR DESCRIPTION
**Pull request by marohrdanz**
This pull request 

1. Runs prettier to standardize formatting of the .js files 
2. Updates our GitHub actions to:
   - Account for whitespace change in CompatibilityManger.js line that contains the version number
   - Remove deprecation warnings about Node 16.
4. Updates third-party GitHub actions to remove deprecation warnings about Node 16.

My fork of the NG-CHM Artifacts repo contains artifacts built from the changes in this PR: https://github.com/marohrdanz/NG-CHM-Artifacts

## 1. Prettier

Ran [prettier](https://prettier.io/docs/en/index.html) with default options:

```bash
prettier --write *.js
```

on WebContent/javascript/*.js and custom.js files. 

I just got tired of trying to understand the code with variable formatting and indentation.

## 2. GitHub Action updates

This run of prettier changed the line in `CompatibilityManager.js` containing the version string from

```javascript
CM.version = "<version number>"
```

to include leading whitespace:

```javascript
  CM.version = "<version number>"
```

I naively thought I could simply add leading whitspace in the action workflow that extracts the version number. E.g.:

```yaml
start_string: '  CM.version = '
```

However GitHub Actions remove leading whitespace from arguments, lolz.

So I updated the github action that extracts the version number from `CompatibilityManager.js`.

I also updated these actions to avoid GitHub's warning that Node 16 is deprecated. These actions have been updated to Node 20.

These updates are reflected in their corresponding repo releases:

- https://github.com/marohrdanz/extract-version-from-file/releases
- https://github.com/marohrdanz/build-number-tag/releases

## 3. Third-party actions update

These version updates were inspired by the Node 16 deprecation warnings.

### CODE REVIEW

**Comment by ChrisWakefield** [comment]
@marohrdanz Does your comment about "My fork of the NG-CHM Artifacts" mean that you have built and tested those artifacts after the Prettier step?

**Comment by marohrdanz** [comment]
FYI: the two force pushes to mary-dev were rebases to 

1. fix a typo in a commit message, and 
3. squash a commit because I initially missed updating the version for github action [softprops/action-gh-release](https://github.com/softprops/action-gh-release) in NG-CHM-Artifiacts_release.yml

**Comment by marohrdanz** [comment]
@ChrisWakefield , I have tested:

- ShaidyMapGen.jar
- ngchmEmbed-min.js
- ngchmWidget-min.js
- server.app
- viewer.source
- GUI builder
- Verified #324 is not present

Are there other tests I should perform? (maybe a topic for today's meeting).

**Review by ChrisWakefield — APPROVED** [review]
As discussed in meeting.

**Review by bmbroom — APPROVED** [review]
Approved based on discussion in weekly NG-CHM meeting.

**Pull request merged**
