### PR TITLE
Restructure part 4

### PR DESCRIPTION
**Pull request by bmbroom**
This is a block of "independent" commits (in spirit at least).  What really unites them is that they are not a reorganization of the detail map modules, which is what's next in my queue of commits.

The first commit moves the user-interface code for saving maps for MatrixManager to the User Interface Manager. This enables a lot of dependencies to be removed from MatrixManager.  The goal is to make MatrixManager a very low-level module that depends on very few other modules.

The second and third commits move redraw functions from UIMGR to more specific modules, allowing circular dependencies on UIMGR to be removed from mid-level modules.

The fourth commit replaces a timeout-driven loop to detect when plugin entries have been defined with a simple wait list that is processed after custom.js is loaded.

The fifth replaces the global currentDL (name of current heat map data layer) with a heat map specific property.  The motivating reason was to enable removal of the dependency on the ColorMapManager on the SelectionManager.  Also the current data layer is really independent of the view shown in each detail panel.

### CODE REVIEW

**Review by jmelott — COMMENTED** [review]
I notice that the changes move the redrawCanvases method to SummaryHeatMapDisplay.js.  Is this just redrawing the canvases that are part of the Summary panel, or is it also causing the detail panels to be redrawn as well?   If it is causing the detail canvases to be redrawn, then should it be in SummaryHeatMapDisplay.js?  If it isn't causing the detail panels to be redrawn, then is the call to DET.setDrawDetailsTimeout (DET.redrawSelectionTimeout); necessary there?

**Comment by bmbroom** [comment]
It is redrawing both all the summary canvases as well as all the detail maps.  This seemed like the best place for it at the time.  I will move it again later, after I restructure both the detail views and the summary views.  I looked at just moving it there directly as part of this patch, but it breaks too many following commits in my queue.

**Review by jmelott — APPROVED** [review]
Given the Detail panel redraw in the Summary panel is a known issue and the plan is to reorganize that in a later commit at some point, I'll approve the pull request.

**Review by ChrisWakefield — APPROVED** [review]
New changes built and the build created correct artifacts.  I examined most -but not all- of the source changes.

**Pull request merged**
