### PR TITLE
Remove version query parameters from files included by chm.html

### PR DESCRIPTION
**Pull request by bmbroom**
Remove version number from files included into chm.html.

Create common CompilerUtilities.java and start using it so we don't
have to duplicate the same logic in every generator tool.

Improve the quality of error messages.

Increase version to 2.21.2.

### CODE REVIEW

**Review by jmelott — CHANGES_REQUESTED** [review]
Can you update the appropriate documentation files in https://github.com/MD-Anderson-Bioinformatics/NG-CHM/tree/master/NGCHM/Documentation to reflect the use of this new code before we merge it into the main branch?   Then I can test the documentation as well.

**Review by marohrdanz — APPROVED** [review]
These seem like reasonable changes to merge into the main branch. 

One thing I should have mentioned back in PR #230 : the server.app doesn't include the favicon (ngChmIcon.ico).

**Comment by bmbroom** [comment]
James: I updated the NG-CHM Versioning and NG-CHM Utility ANT Scripts documents (and converted them to Markdown).

**Review by jmelott — APPROVED** [review]

**Comment by bmbroom** [comment]
I "merged" this manually so I could reorder the commits and put the upgrade to 2.21.2 last.

**Pull request closed without merging**
