### PR TITLE
Add documentation for defining linkouts

### PR DESCRIPTION
**Pull request by bmbroom**
Add documentation for the linkouts interface.

### CODE REVIEW

**Review by jmelott — COMMENTED** [review]
A few questions. Should this also explain the following or will these things be explained elsewhere?
1) How labels for single vs multiple will be displayed in the menus (top or bottom section).
2) How and when plugins will be displayed in the two tabs of the "About Plugins" dialog.
3) How complex labels (divided by | characters) will interact with link outs and plugins.

Other questions:

If the addPlugin-related API interfaces are generally preferred to the equivalent addLinkout interfaces, is there some case where it is necessary to use the latter? 

Do we have the capability to drop-in a plugin on an open map or was that something that was just an experiment that I'm remembering?  If it is included in the current version of the viewer, should that be explained here or elsewhere?

**Comment by bmbroom** [comment]
None of 1-3 affects how link outs are defined.  As far as possible I don't want to make this about NG-CHMs.  I've put some pretty generic comments in just for concreteness in the explanations, but I've tried to make them as generic as possible.

I can't think of any reason to use the addLinkout interfaces.  I strongly considered not including them in this document.  They can still be removed.

Yes, we can drop-in plugins.  That is a different interface (all drop in plugins operate in an iframe via message passing).  We don't need it for now, but we should include them when we get a chance.

**Review by jmelott — COMMENTED** [review]
Do we use the addLinkout interfaces in any of our linkouts?  

If we don't use them in our linkouts code, then I'd lean toward taking them out of the documentation so people would use the preferred ones.

If we do use them in our code, then I'd say leave them in as people might look at our existing code to figure out how things work and not having that part documented would be more confusing, but put the preferred function in the documentation earlier in the documentation so people would be more likely to see and use it first.

**Comment by marohrdanz** [comment]
I like this latest version. I think readers will be able to understand it easily. The only tweaks I might consider are 

- making some of the *italics* into **bold** in the 'Linkout Categories' section (e.g. **Hamburger** instead of *Hamburger*)
- Fixe some odd new line/paragraph things in that section.

**Review by marohrdanz — APPROVED** [review]
I think this document will be helpful to users.

**Review by jmelott — APPROVED** [review]

**Pull request merged**
