### PR TITLE
Restructure part 5

### PR DESCRIPTION
**Pull request by bmbroom**
Fifth set of restructure changes.  Most significant change in this set is the renaming of SelectionManager.js to DetailHeatMapViews.js and the start of changes that flow from that.

### CODE REVIEW

**Comment by marohrdanz** [comment]
This introduces a tiny bug for opening a saved map: RecreatePanes.js used `DEV.flickChange()`, which is now `UIMGR.flickChange`.

**Comment by bmbroom** [comment]
I pushed another commit that addresses the bug Mary found.

**Comment by bmbroom** [comment]
Last night I pushed three additional bug fix commits, making four total.  I think it would be better to have a clean commit history, so I would like to close this pull request, rebase the above to a clean history, and submit an updated pull request. Your thoughts?

**Comment by marohrdanz** [comment]
I'm OK with the extra commits, especially since they reference earlier commits. 

But is there a typo in '6a1125e21' (in the commit message of [67b39a1](https://github.com/MD-Anderson-Bioinformatics/NG-CHM/commit/67b39a180933bd0e2b808b209d2de75df831e161))? I can't seem to find it on GitHub.

**Comment by bmbroom** [comment]
Oops, my bad. 6a1125e21 is on an old rebased branch that never got uploaded to github. Should have been 3704cebc.

**Comment by jmelott** [comment]
Either way works for me.

**Comment by marohrdanz** [comment]
Would it be reasonable/possible to force push rebased changes to this branch instead of opening a new pull request?

**Comment by bmbroom** [comment]
If I don't hear any objections to Mary's idea, I'll try that this afternoon.

**Comment by bmbroom** [comment]
The fixup commits have been applied to the faulty commits and the rebased branch has been force pushed to the restructure branch.  Hopefully ready for approval.

**Review by jmelott — APPROVED** [review]

**Review by marohrdanz — APPROVED** [review]

**Comment by marohrdanz** [comment]
When I open things in the browser and poke around, I get errors related to this bit of code in SearchManager.js:

```js
1024   if (searchTarget === 'row') {
1025     discCovRowState = "";
1026     
1027   } else if (searchTarget === 'column') {
1028     discCovColState = "";
1029     
1030   } else {
1031     discCovRowState = "";
1032     discCovColState = "";
1033   }
```

Maybe these variables are left over from old code?

**Comment by bmbroom** [comment]
That problem gets fixed by the very next commit in my list, so I think I'll just leave them as is for now.

**Pull request merged**
