### PR TITLE
Use Action to build NGCHMSupportFiles artifacts

### PR DESCRIPTION
**Pull request by marohrdanz**
This pull request adds a GitHub action to build and push artifacts to the [NGCHMSupportFiles](https://github.com/MD-Anderson-Bioinformatics/NGCHMSupportFiles) project.

The action is triggered by new releases, and with the following main steps:

- Checks out release tag
- Builds ShaidyMapGen.jar
- Builds ngchmWidget-min.js
- Checks out  the NGCHMSupportFiles project
- Adds ShaidyMapGen.jar and ngchmWidget-min.js to  the NGCHMSupportFiles project
- Updates version number of NGCHMSupportFiles project to match release tag
- Commits and pushes updates back to  the NGCHMSupportFiles project
- Makes release of NGCHMSupportFiles project for new version

The Action is configured to use the DQS-Dev-BCB service account.

### CODE REVIEW

**Review by ChrisWakefield — APPROVED** [review]
I can't say I understand some parts (details) of it, but I'm ok with merging and seeing it work.

**Comment by jmelott** [comment]
I can see one issue.  We've only made tags when new versions of this repo have been released in this repository.  There are no official releases.  If we continue that method of doing things, then this would never run, correct, or is it watching for tags instead of releases? 

As far as using tags, then, I think we only consider the even numbered tags as actual releases.  The odd ones are "development version" tags.  Would we want to automatically push all the odd number versions to the support files as well?

**Comment by ChrisWakefield** [comment]
>> If we continue that method of doing things, then this would never run
You are correct sir.  I believe this supposes we start using the "releases" feature.

>> Would we want to automatically push all the odd number versions to the support files as well?
No.  The 'support files' can just be for release versions.

**Comment by marohrdanz** [comment]
Doh, in all our meetings we use the word 'Release'. I just assumed that meant we were making GitHub releases, but I see that we aren't actually.

**Review by bmbroom — APPROVED** [review]

**Pull request merged**
