### PR TITLE
Detailbuttons

### PR DESCRIPTION
**Pull request by bmbroom**
This is a draft pull request to enable discussion about moving the zoom and display mode buttons to the detail pane header as illustrated by the following screen shot:

DetailButtonsScreenshot

 I see the following advantages:
    - Moves these controls closer to the detail display that they apply to
    - Hides these controls when detail pane is not visible and they don't apply
    - Frees space in the header bar
    - In fullness of time, allows multiple detail panes from a UI perspective.
      (Note that the current code is nowhere near able to do that, and there
       are additional UI issues as well.)

Comments/discussion welcome.

### CODE REVIEW

**Comment by jmelott** [comment]
Overall I think it is a good design choice.
I'm not sure it really buys us any useful space at the top of the screen as, if the screen were at a width such that the sizing would become an issue, then you usually wouldn't have enough space to show them in the detail pane either.
Something to consider would be that if we do this that we should probably either limit the lowest allowable width of the detail pane and/or make these extra controls such that they can be collapsed or expanded or even moved to a pop out window.
I'm not sure that supporting users with tablets or touchscreens is or even should be a major concern for this application, but if you think it is, then there might need to be some addition usability testing regarding having these controls in the new location to see if it interferes with the usability of the detail pane in common use cases like upper dendrogram zooming or working with the column covariates.

**Comment by marohrdanz** [comment]
I think this feature will make the UI slighly more intuitive in the multi-panel interface. If we restrict the width of the detail pane to accomodate these buttons, it might be problematic for users who want to increase the width of panels on the other side of the window. So maybe @jmelott 's suggestion to make the buttons collapse as needed might be more user friendly.

**Comment by bmbroom** [comment]
Additional commit I just added allows the buttons to split into multiple lines when horizontal space is tight.  (If really cramped, it will be one icon per line = 5 lines.)

**Comment by ChrisWakefield** [comment]
I agree they should move into the detail panel, and I agree they should not impose a minimum width on the panel.
I'm concerned this introduces a green/blue color blindness issue, at least as shown in the screenshot.  Is the blue color of the bar indicating something?

Separately, would this be a good time to get rid of the containing table all together, in favor of just css?  It's a one-row table, right?

**Comment by bmbroom** [comment]
I disabled the alternate pane header background for now.  We can decide later whether to drop it completely or use it for something else.

I also removed the top-level table for the "bottom buttons" in the top header.  Note that the "search"
input is actually (still) a table with the number of selected rows & columns on the second line.

**Comment by mstucky** [comment]
I agree with everyone on moving the buttons being more intuitive in an environment that may have many more panels open than just the summary/detail.  This might have been something we would have designed had the summary and detail panels had their own header bars originally.  

 

I would point out, however, that both the scatterplot and pathway mapper tools have their control buttons located in a menu bar below the header bar of the pane.  So, it might be a little inconsistent to embed controls other than the Open Pane and Gear buttons on the bar.  Not necessarily a deal breaker, though.  It would probably not be a lot of fun to attempt to add a bar for the buttons within the detail pane AND it would take away from the visualization space for the detail heat map.

 

I think we would be okay with moving them with regard to sizing on the panels and I’m not sure that I would worry too much about locking the width of the detail pane so that they are always completely visible.  As it stands the minimum sizing on the detail pane allows the gear button to run over the title.  Maybe this is a bug, but any user can understand that they may need to widen the pane to access features on the bar if they make it so narrow that the contents of the window are barely visible anyway.  We could also go ahead and set a minimum to include the tool buttons and the gear.  If this were the case the detail panel would be at it’s last “usable” width (about 2 inches) for visualizing the detail map anyway.  I’m not a fan of a pop-out floating button bar as a solution.

 

I don’t know if this was mentioned but, I believe that the buttons should be right justified on the header bar to line up with the open pane window button, as the gear button is in other panels, for consistency.

 

Another suggestion I might make is to change the header title of the bars from “Summary Heatmap” and “Detail Heatmap” to “Summary” and “Detail”, respectively.  This will allow a little more room for the buttons and resizing.  

 

Also, I thought that we were supposed to refer to a heat map with 2 words.  These headers should be changed to match the nomenclature that we are using on the application header bar and elsewhere.

 

Thanks,

 

Mark Stucky.

In Silico Solutions LLC.

703 402-6146

**Comment by bmbroom** [comment]
Ready to merge this now.  Ideally, into master, but I couldn't see a way to change the target branch,

**Comment by ChrisWakefield** [comment]
@bmbroom Just view the PR, click the Edit button, then change the Target Branch.

**Comment by ChrisWakefield** [comment]
@bmbroom Look for the line that reads "	bmbroom wants to merge 5 commits into ....."

**Comment by mstucky** [comment]
Has the branch Stucky_2.17.2_Viewer already been merged to master or does this branch include all of that logic (meaning both would be merged at the same time with DetailButtons)?

**Comment by ChrisWakefield** [comment]
> Has the branch Stucky_2.17.2_Viewer already been merged to master or does this branch include all of that logic (meaning both would be merged at the same time with DetailButtons)?

Yes, you had already merged that.  Master is now equal to Stucky_2.17.2_Viewer.

**Comment by ChrisWakefield** [comment]
@bmbroom @mstucky "Pull request successfully merged and closed
You’re all set—the detailbuttons branch can be safely deleted."

**Pull request merged**
