### PR TITLE
Enhance detail covariate bar scaling and improve PDF generation

### PR DESCRIPTION
**Pull request by bmbroom**
These are the commits for the system I demoed today.

I still need to fix up covariate bar sizing in the PDF detail views and implement the various changes to the previous pull requests that we discussed.

### CODE REVIEW

**Review by jmelott — APPROVED** [review]

**Comment by bmbroom** [comment]
I pushed a quick patch to fix the PDF generator failing when they are too many categories to print.  This bug is also present is the main branch but its presentation is more subtle: it fails to print at least one covariate after the one that fails.  For the Lake heatmap, it prints a warning that it can't output the Plate covariate, but it fails to output *anything* about the Cell type covariate that follows.

**Comment by bmbroom** [comment]
So I fixed both the initial strange dendrogram view and the PDF generation issue triggered by the Lake NG-CHM.

Anything else I still need to address?

**Comment by bmbroom** [comment]
Commit 03a77f4 should fix the major show stopper problems with detail map sizing.

There are still relatively minor problems with label positioning.  Unfortunately, I think that fixing those issues will require a major rewrite (beyond the scope of this pull request).

I have also noticed a problem with single (or a few) covariate bar(s) on very large maps being too small. Will look into that next.

**Review by marohrdanz — APPROVED** [review]
I tested some of the issues in our email exchanges, and the showstopper ones appear resolved. 

The general idea of this PR is something we all agree on I think. At this point, the pull request has grown so large that perhaps the best thing to do is merge into the main branch and open GitHub issues as needed?

**Pull request merged**
