### PR TITLE
Insilico html heat map

### PR DESCRIPTION
**Pull request by bmbroom**
I made a couple of modifications to enable HTML generation from R:

- Pass -HTML option through ShaidyRMapGen to the heatmapGenerator
- Allow location of ngchmWidget-min.js to use to be specified via an environment variable

Needs to be merged with the main line.

### CODE REVIEW

**Comment by mstucky** [comment]
I see that this is a draft pull request but, there's a lot going on here that is appears to be unrelated to the html heat map changes as a result of all of the change in the code base since early May.  Particularly changes to chm.html.  Another good example would be the GalaxyMapGen change in here that is trying to change the version from 2.11.0 to 2.11.1, whereas we are now on 2.12.0.   I would be more comfortable laying in the HTML heat map changes over the current master branch, doing some quick testing, and pushing up a new pull request tied to a new branch.  I can add all of Bradley's code changes to that branch as well.

**Comment by ChrisWakefield** [comment]
@bmbroom 
I agree with @mstucky that the changes to
chm.html, DetailHeatMapDisplay.js, and GalaxyMapGen.java
are unrelated and should not be in this PR.  If I'm reading this correctly, the unrelated changes were commits b2a87a9, 017a47c, and part of dc99188.  However, the remainder of that last one is required for this HTML feature, plus all 3 of BMB's commits.  It sounds like Mark has a good plan to move forward.

**Comment by bmbroom** [comment]
I agree.  I did it this way just to get it looked at.

**Comment by mstucky** [comment]
Closing this request after #50 was merged in its place.

**Pull request closed without merging**
