### PR TITLE
Changes about linkout version numbers

### PR DESCRIPTION
**Pull request by ChrisWakefield**
Increase version number for linkouts changed in 43ff6d8, uncommented version for Antibody RRID

### CODE REVIEW

**Comment by marohrdanz** [comment]
Can we also remove the "Version" column in the user display? Initial check suggests the following, shown as git diff of `UserHelpManager.js`, will work:

```diff
@@ -1132,9 +1132,7 @@ NgChm.UHM.openAllLinkoutsHelp = function() {
                        //If first plugin being written to table, write header row.
                        if (validPluginCtr === 0) {
                                tr.className = "chmHdrRow";
-                               var td = tr.insertCell(0);
-                               td.innerHTML = "<b>Version</b>";
-                               td = tr.insertCell(0);
+                               let td = tr.insertCell(0);
                                td.innerHTML = "<b>Description</b>";
                                td = tr.insertCell(0);
                                td.innerHTML = "<b>Name</b>";
@@ -1160,9 +1158,6 @@ NgChm.UHM.openAllLinkoutsHelp = function() {
                        var tdDesc = tr.insertCell(2);
                        tdDesc.className = "chmTblCell";
                        tdDesc.innerHTML = plugin.description;
-                       var tdVersion = tr.insertCell(3);
-                       tdVersion.className = "chmTblCell";
-                       tdVersion.innerHTML = plugin.version;
        }
        return pluginTbl;
```

**Comment by ChrisWakefield** [comment]
Included your suggestion in this PR.

**Review by marohrdanz — APPROVED** [review]
Looks good to me.

**Comment by ChrisWakefield** [comment]
@marohrdanz Now I see that version column is in two different places for the two panels of the help dialog.  Did we decide to remove it from both?  That would mean this is still incomplete.

**Comment by marohrdanz** [comment]
I think you're right @ChrisWakefield . Probably the similar code in `NgChm.UHM.openMapLinkoutsHelp`?

**Review by bmbroom — APPROVED** [review]

**Review by marohrdanz — APPROVED** [review]
Looks as we have discussed.

**Pull request merged**
