### PR TITLE
Update ribbon mode dendrogram selection when changing detail maps

### PR DESCRIPTION
**Pull request by bmbroom**
Updates the behavior of the ribbon mode dendrogram selection as we discussed.

Tracks whether each detail view's ribbon mode focus area is a dendrogram selection. Initially false. Set to true if the user selects a dendrogram branch on the summary map.  Cleared if the user uses keyboard navigation to change the focus area (and displays a popup allowing the user to reset the focus region if desired).

Also used to update dendrogram ribbon mode highlight when switching between detail maps or when restoring saved maps.

Fixes issue #372.

### CODE REVIEW

**Comment by marohrdanz** [comment]
Is it possible there is a missed initialization of `restoreInfo` in UI-Manager? I get errors about it when trying to play around with this branch, and I only see it initialized in RecreatePanes.

**Comment by bmbroom** [comment]
Should be fixed now.

**Comment by marohrdanz** [comment]
I know we talked about it at the meeting, but I'm worried users will become annoyed by that popup they have to click every time. Maybe we could let them just hit 'enter' to accept the change? (their fingers are on the keyboard and not on the mouse when the popup shows up). Is anyone else worried about this?

**Comment by bmbroom** [comment]
My last two commits address Mary's latest comment.  It's okay as is, but I'm concerned about the consistency of the response to 'Enter' across the whole UI.  See comments in the last commit for details.

**Review by marohrdanz — APPROVED** [review]
Approving with the caveat that we'll make changes discussed at today's meeting regarding the dialog popup (basically plan to remove that dialog).

**Review by jmelott — APPROVED** [review]

**Pull request merged**
