### PR TITLE
Misc. bug fixes including alternate approach to saving layout state

### PR DESCRIPTION
**Pull request by bmbroom**
First two commits below (d6365d6, f57c184) address issues #223, #226.

Third commit (d2f870e) reimplements the saving and restoring the layout state. The layout state is now saved using custom logic that captures the semantic features of
the panels (e.g. whether a panel is collapsed, expanded, etc.). This way we can avoid saving lots of unwanted details to the saved-state.  Addresses #228.

I also made the determination of panel types more robust by explicitly save panel
types and plugin names. 

NOTE: Saved-state from this pull request is incompatible with saved-state from the original approach.

### CODE REVIEW

**Comment by marohrdanz** [comment]
This looks a lot more straightforward than what I was doing. I was hoping someone who understood the panel code better than I do would be able to come up with something cleaner.

**Comment by bmbroom** [comment]
Commit 4b45954 addresses #224.  It breaks compatibility with maps saved using
earlier unreleased versions of the viewer.

**Comment by bmbroom** [comment]
Commit b7115c7 addresses #203.

**Comment by bmbroom** [comment]
Commit 691c3f6 addresses #193.

**Review by jmelott — APPROVED** [review]

**Review by marohrdanz — APPROVED** [review]
Approving only in order to allow a merge to work on issues related to these changes.

**Pull request merged**
